# GitHub Sponsors
# This account must have GitHub Sponsors enabled for the Sponsor button to work.
github: [hglabplh-tech]

# Optional alternatives. Uncomment only after configuring the respective account.
# patreon:
# open_collective:
# ko_fi:
# tidelift:
# community_bridge:
# liberapay:
# issuehunt:
# lfx_crowdfunding:
# polar:
# buy_me_a_coffee:
# thanks_dev:
# custom:
